name: Deployment pipeline

on:
  push:
    branches:
      - main
    pull-request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: end-to-end testing
        uses: cypress-io/github-action@v2
        env:
          TEST_DB_URL: ${{ secrets.TEST_DB_URL }}
          PORT: 3001
        with:
          env: true
          command: yarn test
          start: yarn start:cypress
          wait-on: http://localhost:3001
      - name: install doctl (digitalocean deployment tool)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: deploy on digitalocean
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}